"""add timestamps

Revision ID: 0001
Revises: 0000
Create Date: 2026-03-24 04:11:56.940816

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = "0000"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    file_cols = {c["name"] for c in inspector.get_columns("file_metadata")}
    if "created_at" not in file_cols:
        op.add_column(
            "file_metadata",
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        )

    token_cols = {c["name"] for c in inspector.get_columns("oneshot_tokens")}
    if "created_at" not in token_cols:
        op.add_column(
            "oneshot_tokens",
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        )

    op.execute("UPDATE file_metadata SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    op.execute("UPDATE oneshot_tokens SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    token_cols = {c["name"] for c in inspector.get_columns("oneshot_tokens")}
    if "created_at" in token_cols:
        op.drop_column("oneshot_tokens", "created_at")

    file_cols = {c["name"] for c in inspector.get_columns("file_metadata")}
    if "created_at" in file_cols:
        op.drop_column("file_metadata", "created_at")
    # ### end Alembic commands ###
