"""add token expiration

Revision ID: b08128e4dc1c
Revises: 0001
Create Date: 2026-03-24 15:07:03.763684

"""
from collections.abc import Sequence
from datetime import UTC, datetime, timedelta

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b08128e4dc1c"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    token_cols = {c["name"] for c in inspector.get_columns("oneshot_tokens")}
    if "expires_at" not in token_cols:
        op.add_column("oneshot_tokens", sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True))

    token_table = sa.table("oneshot_tokens", sa.column("expires_at", sa.DateTime(timezone=True)))
    op.execute(
        token_table.update()
        .where(token_table.c.expires_at.is_(None))
        .values(expires_at=datetime.now(UTC) + timedelta(hours=48))
    )

    indexes = {i["name"] for i in inspector.get_indexes("oneshot_tokens")}
    index_name = op.f("ix_oneshot_tokens_expires_at")
    if index_name not in indexes:
        op.create_index(index_name, "oneshot_tokens", ["expires_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    indexes = {i["name"] for i in inspector.get_indexes("oneshot_tokens")}
    index_name = op.f("ix_oneshot_tokens_expires_at")
    if index_name in indexes:
        op.drop_index(index_name, table_name="oneshot_tokens")

    token_cols = {c["name"] for c in inspector.get_columns("oneshot_tokens")}
    if "expires_at" in token_cols:
        op.drop_column("oneshot_tokens", "expires_at")
    # ### end Alembic commands ###
